<?php
$url = "https://vnexpress.net/rss/so-hoa.rss"; // xmld.xml contains above data
// $feeds = file_get_contents($url);
// $rss = simplexml_load_string($feeds);

$doc = new DOMDocument();
$doc->load($url);
$Feeds = array();

foreach ($doc->getElementsByTagName('item') as $node) {
    $itemRSS = array (
        'title' => $node->getElementsByTagName('title')->item(0)->nodeValue,
        'desc' => $node->getElementsByTagName('description')->item(0)->nodeValue,
        'link' => $node->getElementsByTagName('link')->item(0)->nodeValue,
        'date' => $node->getElementsByTagName('pubDate')->item(0)->nodeValue
        );
    array_push($Feeds, $itemRSS);
}
// print_r($items);
?>
<p><?php
    // var_dump($Feeds) 
 ?></p>


<?php 
    ?>
    <div style="display: -webkit-box;width: 100%;overflow: scroll;" >
    <?php                
     foreach($Feeds as $temp){ 
        ?>
        <div class="content" 
        style="width: 245px; padding-bottom: 20px; margin: 8px;">
            <div class="title">
                <p style="font-weight:700;
                    font-size: 16px;"><?php echo $temp['title'] ?></p>
            </div>
            <div class="desc">
                <p
                ><?php echo $temp['desc'] ?></p>
            </div>
            <div class="date">
                <p style="font-size: 12px; font-style: italic;"><?php echo $temp['date'] ?></p>
            </div>
        </div>
        <?php
    }
    ?>
    </div>
    <?php
?>